import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Homepage/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`container mx-auto px-4 py-8`}
      >
        <Navbar />
        <main className="">
          {children}
        </main>
      </body>
    </html>
  );
}
